### ISSUE TITLE
my_factorial function in Basic Computing 2 cannot handle edge cases

### ISSUE THREAD

**Issue by gracilis** [StefanoAllesina/BSD-QBio4#6]
**Describe the bug**
The my_factorial example function in Basic Computing 2 returns incorrect answers if the input is 0 or 1

**To Reproduce**
my_factorial <- function(a = 6){
  if (as.integer(a) != a) {
    print("Please enter an integer!")
  } else {
    tmp <- 1
    for (i in 2:a){
      tmp <- tmp * i
    }
    print(paste(a, "! = ", tmp, sep = ""))
  }
}

> my_factorial(1)
[1] "1! = 2"
> my_factorial(0)
[1] "0! = 0"

**FIX:**
explicitly code in behavior in edge cases

**Comment by sepalmer** [comment]
Fixed! I changed the if-then so it asks for a positive integer (i.e. not 0 or negative nums), and fixed the for loop so that it returns 1! = 1.
